# Generated by Django 3.1.5 on 2021-01-15 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_local', models.CharField(max_length=20)),
                ('when_started', models.DateField()),
                ('when_end', models.DateField()),
                ('job', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
                ('exp_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('link_github', models.URLField(max_length=150)),
                ('link_linkedin', models.URLField(max_length=150)),
                ('avatar', models.ImageField(upload_to='#')),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portify.experience')),
                ('skills_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portify.skills')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
