# Generated by Django 3.1.5 on 2021-01-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portify',
            name='avatar',
            field=models.URLField(max_length=150),
        ),
    ]
