# Generated by Django 3.1.5 on 2021-01-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portify', '0002_auto_20210115_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portify',
            name='experience_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portify.experience'),
        ),
        migrations.AlterField(
            model_name='portify',
            name='skills_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portify.skills'),
        ),
    ]
